# Generated by Django 5.1.7 on 2026-03-12 09:31

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_article_ai_summary_article_ai_summary_generated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAutocomplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=100, unique=True)),
                ('suggestion_count', models.PositiveIntegerField(default=0)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_searched'],
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('content_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_index', to='articles.article')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['title_vector'], name='search_sear_title_v_9098cd_gin'), django.contrib.postgres.indexes.GinIndex(fields=['content_vector'], name='search_sear_content_5405d4_gin')],
            },
        ),
    ]
