# Generated by Django 5.1.7 on 2026-03-12 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_article_ai_summary_article_ai_summary_generated_at_and_more'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('local', 'Local Model')], max_length=50)),
                ('model_id', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIHeadlineSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_headline', models.CharField(max_length=300)),
                ('short_headline', models.CharField(max_length=100)),
                ('social_headline', models.CharField(max_length=150)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('was_used', models.BooleanField(default=False)),
                ('suggested_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_headline_suggestions', to='articles.article')),
            ],
            options={
                'ordering': ['-relevance_score'],
            },
        ),
        migrations.CreateModel(
            name='AITagSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0, help_text='0.0 to 1.0')),
                ('was_approved', models.BooleanField(blank=True, help_text='True if approved, False if rejected', null=True)),
                ('suggested_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tag_suggestions', to='articles.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='tags.tag')),
            ],
            options={
                'ordering': ['-confidence_score'],
                'unique_together': {('article', 'tag')},
            },
        ),
    ]
